[[redirects]]
  from = "/api/*"
  to = "https://backarcanus.onrender.com/api/:splat"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "*", Access-Control-Allow-Credentials = "true" }
